# Generated by Django 5.1.3 on 2024-12-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
