# Generated by Django 5.1.3 on 2024-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('front_page', models.ImageField(upload_to='')),
                ('project_file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
