# Generated by Django 5.1.3 on 2024-12-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
