# Generated by Django 5.1.3 on 2024-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='front_page',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='project_file',
            field=models.FileField(upload_to='file'),
        ),
    ]
